### ISSUE TITLE
CSS .modal

### ISSUE THREAD

**Issue by flean** [grovelabs/meteor-spark.js#1]
Your CSS is to general and causes issues with bootbox.js. Can you limit your css to your package? Thanks

**Comment by cmnjcs** [comment]
Hi @flean, can you please provide a specific pointer? Looking at the source for the `meteor-spark` package (which can be found [here](https://github.com/spark/sparkjs)), I only see [one CSS file](https://github.com/spark/sparkjs/blob/master/lib/spark-browser-style.css), and its selectors are pretty specific.

**Comment by flean** [comment]
When I add your package it adds a style tag under the script tag that has the spark login modal css. It's applied globally.

**Comment by flean** [comment]
Your package doesn't add `.spark-modal` it adds `.modal`

**Comment by flean** [comment]
![screen shot 2015-04-01 at 4 51 22 pm](https://cloud.githubusercontent.com/assets/1794772/6955210/5fa99b58-d88f-11e4-9f89-08288e0cd906.png)

**Comment by cmnjcs** [comment]
Ok, we've updated this package to reflect `0.4.1`, the most-recently minified version of the source package. That solves this issue, in that the CSS selectors were made more specific. Our package has been published.

Just a heads up--as far as we can tell, you can't limit CSS to a package like you were asking for. If you're aware of a way to do that, happy to hear about it.

One last note--FYI, we're just wrapping the `spark:spark.js` package for Meteor. If you were to look at their issues list, you'd have seen [this issue](https://github.com/spark/sparkjs/issues/45), which is the problem you had. Point is--problems are probably best searched for first there, and if it's been marked as fixed, let us know and we'll make sure we're updating appropriately.
